# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("auth.proto", :syntax => :proto3) do
    add_message "InternalApi.Auth.AuthenticateRequest" do
      optional :token, :string, 1
    end
    add_message "InternalApi.Auth.AuthenticateWithCookieRequest" do
      optional :cookie, :string, 1
      optional :remember_user_token, :string, 2
    end
    add_message "InternalApi.Auth.AuthenticateResponse" do
      optional :authenticated, :bool, 1
      optional :name, :string, 3
      optional :user_id, :string, 4
      optional :id_provider, :enum, 5, "InternalApi.Auth.IdProvider"
    end
    add_enum "InternalApi.Auth.IdProvider" do
      value :ID_PROVIDER_UNSPECIFIED, 0
      value :ID_PROVIDER_API_TOKEN, 1
      value :ID_PROVIDER_GITHUB, 2
      value :ID_PROVIDER_BITBUCKET, 3
      value :ID_PROVIDER_GITLAB, 4
      value :ID_PROVIDER_OKTA, 5
      value :ID_PROVIDER_REMEMBER_ME_TOKEN, 6
    end
  end
end

module InternalApi
  module Auth
    AuthenticateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InternalApi.Auth.AuthenticateRequest").msgclass
    AuthenticateWithCookieRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InternalApi.Auth.AuthenticateWithCookieRequest").msgclass
    AuthenticateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InternalApi.Auth.AuthenticateResponse").msgclass
    IdProvider = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InternalApi.Auth.IdProvider").enummodule
  end
end
